server:
  port: 8082

logging:
  level:
    com.zhoutianyu.learnspringboot: info
    org.springframework.web: info

spring:
  redis:
      # Redis 数据库索引（默认为 0）
      database: 0
      # Redis 服务器地址
      host: localhost
      # Redis 服务器连接端口
      port: 6379
      password:
      timeout: 10s
      lettuce:
          pool:
              #连接池最大连接数（使用负值表示没有限制） 默认 8
              max-active: 50
              #连接池中的最大空闲连接 默认 8
              max-idle: 8
              #连接池中的最小空闲连接 默认 0
              min-idle: 0
