server:
  servlet:
    #项目根目录
    context-path: /study/springboot
spring:
  #激活的分支
  profiles:
    active: dev
  #上传文件使用
  servlet:
    multipart:
      #单个文件最大上传大小
      max-file-size: 10MB
      #每次请求上传文件大小最大值
      max-request-size: 30MB

pagehelper:
  #当前数据库
  helperDialect: mysql
  #pageNum<=0 ,query first page
  #pageNum > max count , query last page
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#自定义参数
define:
  nginx:
  #windows path
     #path: D:\upload\
  #linux path
     path: /etc/upload/



