server:
  servlet:
    #项目根目录
    context-path: /study/springboot
spring:
  #激活的分支
  profiles:
    active: dev

logging:
  #配置日志位置
  file: /opt/logs/web-learn-springboot/web-learn-springboot.out
  #配置日志输出格式（定位到哪行输出，方便排查）
  pattern:
      console: '%d{HH:mm:ss.SSS} %-5level %logger{36} [%line] - %msg%n'





