server:
  servlet:
    #项目根目录
    context-path: /study/springboot
spring:
  #激活的分支
  profiles:
    active: dev
  banner:
    charset: UTF-8
  http:
    encoding:
      force-response: true


mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml